language: csharp
solution: ZJBlog.sln
cache: 
 - apt
 - directories:
   - packages
install:
  - nuget restore ZJBlog.sln
script:    # the following commands are just examples, use whatever your build process requires
  - xbuild /p:Configuration=Release /verbosity:minimal ZJBlog.sln
